name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  manual-run:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "👋 This workflow was triggered manually with no input!"
