name: Scheduled Workflow

on:
  schedule:
    - cron: '1 * * * *'  # Every 1 minute

jobs:
  scheduled-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hello on Schedule
        run: echo "⏰ Hello! This job runs every one minute."
